---
title: "CRA Sentiment Analysis"
author: "Alex Lehmann 101061620"
date: "05/04/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readxl)
library(tidyverse)
library(tidytext)
```

## Loading Data
```{r load}
# Translated responses =========================================================
responses <- read_xlsx("../masterResponse.xlsx") %>%
  select(-response) %>%
  rename(
    internal_id = c_1,
    language = c_2,
    question = column,
    response = english
  ) %>%
  select(-`...1`)

# Augment with survey MC responses =============================================
# Load -------------------------------------------------------------------------
survey <- read_xlsx("../Redacted FAB_Project_raw_data_Clean EXCEL Dec.23.xlsx")
colnames(survey) = c(
                     "internal_id",
                     "language",
                     "status",
                     "date",
                     "region",
                     "area1",
                     "area2",
                     "area3",
                     "area4",
                     "area5",
                     "cra_tenure",
                     "fab_tenure",
                     "tools_training",
                     "c_14",
                     "corporate_knowledge",
                     "innovation",
                     "share_ideas",
                     "heard",
                     "know_clients",
                     "clients_understand",
                     "comm_preference",
                     "c_22",
                     "timely_response",
                     "prevents_service1",
                     "prevents_service2",
                     "prevents_service3",
                     "prevents_service4",
                     "prevents_service5",
                     "prevents_service6",
                     "c_30",
                     "prevents_service7",
                     "importance1",
                     "importance2",
                     "importance3",
                     "importance4",
                     "importance5",
                     "importance6",
                     "importance7",
                     "policy_improve",
                     "c_40",
                     "c_41",
                     "compliments",
                     "c_43",
                     "excellent_service",
                     "c_45",
                     "c_46",
                     "can_contact",
                     "c_48"
                   )

# Clean MC responses -----------------------------------------------------------
survey = survey %>%
  select(-c(language, status, date), -starts_with("c_")) %>%
  mutate(
    # Combine separated columns
    area = coalesce(area1, area2, area3, area4, area5),
    prevents_service = coalesce(
                         prevents_service1,
                         prevents_service2,
                         prevents_service3,
                         prevents_service4,
                         prevents_service5,
                         prevents_service6,
                         prevents_service7
                       ),
    .keep = "unused"
  )

# Augment text data ------------------------------------------------------------
responses = full_join(responses, survey, by = "internal_id")
```

## Cleaning 
```{r clean}
clean <- responses %>%
  
  # Standardize word representation --------------------------------------------
  mutate(
    response = str_to_lower(response),
    response = str_replace_all(response, "[^[[:alnum:]]']", " "),
    response = str_replace_all(response, "\\s{2,}", " ")
  ) %>%
  
  # Remove empty responses -----------------------------------------------------
  drop_na()
```

## Tokenizing
```{r tokenize}
tokens <- clean %>%
  
  # Convert responses to list-column for purrr ---------------------------------
  nest(cols = response) %>%
  rename(tokens = cols) %>%
  
  # Tokenize -------------------------------------------------------------------
  mutate(
    tokens = map(tokens, unnest_tokens,
               input = response, output = bigram,
               token = "ngrams", n = 2
             ),
    tokens = map(tokens, separate,
               col = bigram,
               into = c("preword", "word"),
               sep = " "
             )
  )
```

## Map Sentiments
```{r sentiments}
# Helper function to map sentiments within a list-column =======================
map_sents <- function(tokens,
                      lexicon, 
                      neg_dict = c("no", "not", "isn't", "don't", "didn't")) {
  for (lex in lexicon) {
    cur_cols = colnames(tokens) # To update column names later
    
    # Map sentiments -----------------------------------------------------------
    tokens <- inner_join(tokens, get_sentiments(lex), by = "word")
    colnames(tokens)[ncol(tokens)] = "sentiment"
    
    # Convert sentiments to numeric --------------------------------------------
    tokens <- tokens %>%
      filter(sentiment %in% c("positive", "negative") | sentiment %in% -5:5) %>%
      mutate(
        sentiment = ifelse(sentiment == "positive", 1, sentiment),
        sentiment = ifelse(sentiment == "negative", -1, sentiment),
        sentiment = as.numeric(sentiment)
      ) %>%
      
      # Handle negation --------------------------------------------------------
      mutate(sentiment = ifelse(preword %in% neg_dict, -1*sentiment, sentiment))
    
    # Update column names ------------------------------------------------------
    colnames(tokens) <- c(cur_cols, lex)
  }
  
  tokens
}

# Map sentiments ===============================================================
sents <- mutate(tokens,
           sents = map(tokens, map_sents, lexicon = c("nrc", "bing", "afinn")),
           nrc = map_dbl(sents, ~ sum(.x$nrc)),
           bing = map_dbl(sents, ~ sum(.x$bing)),
           afinn = map_dbl(sents, ~ sum(.x$afinn))
         )
```

## Analyze Sentiment
```{r analyze_cats}
# Overall sentiments by worker properties ######################################
# Helper function ==============================================================
sents_by_cats = function(var, sents) {
  sents %>%
    group_by(eval(as.name(var))) %>%
    summarize(across(any_of(c("nrc", "bing", "afinn")), mean), .groups = "drop") %>%
    rename(var = `eval(as.name(var))`)
}

# Get overall sentiments =======================================================
# By worker information --------------------------------------------------------
region_sents = sents_by_cats("region", sents)
area_sents = sents_by_cats("area", sents)
cra_tenure_sents = sents_by_cats("cra_tenure", sents)
fab_tenure_sents = sents_by_cats("fab_tenure", sents)
language_sents = sents_by_cats("language", sents)

# Per question -----------------------------------------------------------------
question_sents = sents_by_cats("question", sents)

# Visualize ====================================================================
# Helper function for barplotting ----------------------------------------------
sents_barplot = function(sents, lex) {
  ggplot(sents, aes(x = var, y = eval(as.name(lex)))) +
    geom_bar(stat = "identity") +
    ylab(lex)
}

# Helper function for lineplotting ---------------------------------------------
sents_lineplot = function(sents, lex) {
  ggplot(sents, aes(x = var, y = eval(as.name(lex)))) +
    geom_line() + 
    ylab(lex)
}

# Generate plots ---------------------------------------------------------------
# Region
sents_barplot(region_sents, "nrc") + xlab("Region")
sents_barplot(region_sents, "bing") + xlab("Region")
sents_barplot(region_sents, "afinn") + xlab("Region")

# Work area
sents_barplot(area_sents, "nrc") + xlab("Area") + coord_flip()
sents_barplot(area_sents, "bing") + xlab("Area") + coord_flip()
sents_barplot(area_sents, "afinn") + xlab("Area") + coord_flip()

# Language
sents_barplot(language_sents, "nrc") + xlab("Language")
sents_barplot(language_sents, "bing") + xlab("Language")
sents_barplot(language_sents, "afinn") + xlab("Language")

# Question
sents_barplot(question_sents, "nrc") + xlab("Question")
sents_barplot(question_sents, "bing") + xlab("Question")
sents_barplot(question_sents, "afinn") + xlab("Question")

# CRA tenure
cra_tenure_sents %>%
  mutate(var = factor(var, 
                 levels = c(
                            "0 to 2 years",
                            "3 to 4 years",
                            "5 to 10 years",
                            "11 to 20 years",
                            "21 + years"
                          )
               )) %>%
  pivot_longer(!var, names_to = "lex", values_to = "sent") %>%
  ggplot(aes(x = var, y = sent, group = lex, color = lex)) +
  geom_line() +
  xlab("CRA Tenure")

# FAB tenure
fab_tenure_sents %>%
  mutate(var = factor(var, 
                 levels = c(
                            "0 to 2 years",
                            "3 to 4 years",
                            "5 to 10 years",
                            "11 to 20 years",
                            "21 + years"
                          )
               )) %>%
  pivot_longer(!var, names_to = "lex", values_to = "sent") %>%
  ggplot(aes(x = var, y = sent, group = lex, color = lex)) +
  geom_line() +
  xlab("FAB Tenure")
```
